# Generated by Django 4.2.17 on 2025-02-08 11:34

from django.db import migrations, models
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='token_expira',
            field=models.DateTimeField(default=quiz.models.default_expiration),
        ),
    ]
