# Generated by Django 4.2.17 on 2025-02-08 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import quiz.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0002_perfilusuario_token_expira'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoActivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_activacion', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('token_expira', models.DateTimeField(default=quiz.models.default_expiration)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_activacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
