# Generated by Django 4.2.20 on 2025-05-17 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0003_codigoactivacion_delete_perfilusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresoTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('estudiar', 'Estudiar'), ('repasar', 'Repasar')], max_length=20)),
                ('filtro', models.IntegerField()),
                ('pregunta_actual', models.IntegerField(default=0)),
                ('preguntas_id', models.JSONField()),
                ('respuestas_correctas', models.IntegerField(default=0)),
                ('respondidas', models.JSONField(default=list)),
                ('completado', models.BooleanField(default=False)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpenAIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_count', models.IntegerField(default=0)),
                ('last_reset', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='openai_usage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
