# Generated by Django 4.2.20 on 2025-05-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_openaiusage_progresotest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='progresotest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='progresotest',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progresotest',
            name='finalizado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progresotest',
            name='tipo',
            field=models.CharField(choices=[('estudiar', 'Estudiar'), ('repasar', 'Repasar')], max_length=20),
        ),
    ]
