# Generated by Django 4.2.20 on 2025-05-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_progresotest_openaiusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresotest',
            name='id_contenido',
            field=models.IntegerField(default=0),
        ),
    ]
