# Generated by Django 4.2.20 on 2025-05-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_progresotest_id_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresotest',
            name='filtro',
            field=models.CharField(max_length=10),
        ),
    ]
