# Generated by Django 4.2.20 on 2025-05-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_progresotest_filtro'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresotest',
            name='totalRespondidas',
            field=models.IntegerField(default=0),
        ),
    ]
