# Generated by Django 4.2.17 on 2024-12-07 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0002_alter_pregunta_respuesta_correcta'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
