# Generated by Django 4.2.17 on 2024-12-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_asignatura_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='fallos',
            field=models.IntegerField(default=0),
        ),
    ]
