# Generated by Django 4.2.17 on 2024-12-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_pregunta_fallos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='ayuda',
            field=models.TextField(null=True),
        ),
    ]
